apiVersion: webapp.crdlego.com/v1
kind: WebApp
metadata:
  name: my-webapp
spec:
  image: nginx:latest
  replicas: 2
  configData:
    test: "todayistutututu"
  ingress:
    enabled: true
    host: "host"
    path: "/main"
    tls: false 
